spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.107:3306/mytest?characterEncoding=utf8&&useSSL=false # url, 进行字符集设置, 与连接方式ssl的禁用
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 9990